name: nsc2026
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - arrow-cpp=21.0.0=h6358905_1
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - blas=1.0=mkl
  - bokeh=3.8.2=py311haa95532_0
  - bottleneck=1.4.2=py311h540bb41_1
  - brotlicffi=1.2.0.0=py311h885b0b7_0
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=h2c209ce_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - cffi=2.0.0=py311h02ab6af_1
  - click=8.2.1=py311haa95532_1
  - cloudpickle=3.1.2=py311haa95532_0
  - colorama=0.4.6=py311haa95532_0
  - contourpy=1.3.3=py311h214f63a_0
  - cycler=0.12.1=py311haa95532_0
  - dask=2025.12.0=py311haa95532_0
  - dask-core=2025.12.0=py311haa95532_0
  - distributed=2025.12.0=py311haa95532_0
  - expat=2.7.3=h9214b88_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py311h02ab6af_0
  - freetype=2.14.1=hfbffc0b_0
  - fsspec=2026.1.0=py311h4442805_0
  - gflags=2.2.2=hd77b12b_1
  - glog=0.5.0=hd77b12b_1
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=12.3.0=h3ef6528_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.7.0=py311haa95532_0
  - iniconfig=2.3.0=py311haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jinja2=3.1.6=py311haa95532_0
  - jpeg=9f=ha349fce_0
  - kiwisolver=1.4.9=py311h03f52e7_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.17.0=h6e672f4_1
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libgrpc=1.71.0=hf4237ab_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.22.1=hb237eb7_0
  - libllvm20=20.1.8=h3aa9ab2_0
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h64815fc_1
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.22.0=ha2884a9_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - llvmlite=0.46.0=py311hd5b4e5d_0
  - locket=1.0.0=py311haa95532_0
  - lz4=4.4.5=py311hb1efef3_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py311h827c3e9_0
  - matplotlib=3.10.8=py311haa95532_0
  - matplotlib-base=3.10.8=py311h26e45b9_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py311h0b37514_0
  - mkl_fft=2.1.1=py311h300f80d_0
  - mkl_random=1.3.0=py311ha5e6156_0
  - msgpack-python=1.1.1=py311h5da7b33_0
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - narwhals=2.7.0=py311haa95532_0
  - numba=0.63.1=py311h54bf9d2_0
  - numexpr=2.14.1=py311h7660c64_0
  - numpy=2.3.5=py311h050da96_0
  - numpy-base=2.3.5=py311h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.0=hf43e1a1_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=2.3.3=py311h42c1672_1
  - partd=1.4.2=py311haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py311h096bfcc_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h4043f72_0
  - pluggy=1.5.0=py311haa95532_0
  - psutil=7.0.0=py311h02ab6af_1
  - pyarrow=21.0.0=py311h42c1672_1
  - pycparser=2.23=py311haa95532_0
  - pygments=2.19.2=py311haa95532_0
  - pyparsing=3.2.5=py311haa95532_0
  - pyqt=6.9.1=py311h12ec796_0
  - pyqt6-sip=13.10.2=py311h630b2a1_0
  - pysocks=1.7.1=py311haa95532_1
  - pytest=9.0.2=py311haa95532_0
  - python=3.11.9=he1021f5_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - python-lmdb=1.7.5=py311h5823743_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - pytz=2025.2=py311haa95532_0
  - pyyaml=6.0.3=py311hb9a58be_0
  - qtbase=6.9.2=h3266e9d_6
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - scipy=1.16.3=py311hbd6d557_0
  - setuptools=80.10.2=pyh332efcf_0
  - sip=6.12.0=py311h706e071_0
  - six=1.17.0=py311haa95532_0
  - snappy=1.2.2=hab6b7b3_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tblib=3.2.2=py311haa95532_0
  - tk=8.6.13=h6ed50ae_3
  - toolz=1.1.0=py311haa95532_0
  - tornado=6.5.4=py311h02ab6af_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.3=py311haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=py311haa95532_1
  - xyzservices=2025.4.0=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zict=3.0.0=py311haa95532_1
  - zipp=3.23.0=py311haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0

prefix: "C:\\Users\\tobia\\.local\\share\\mamba\\envs\\nsc2026"
